### ISSUE TITLE
Mandatory process.env.NODE_ENV replacement

### ISSUE THREAD

**Issue by vuode** [mrsteele/dotenv-webpack#483] opened 2021-12-27 11:32 UTC
Hello! I've notices, that `process.env.NODE_ENV` is always replaced with `mode` from webpack config, unless you provide another value in `.env` file, while the `systemvars` option is not set to `true`. As [documentation](https://webpack.js.org/configuration/mode/) says, webpack uses DefinePlugin under the hood for this replacement.

I suggest making a notice somewhere about this, because it may be confusing, even though tests are written with this behaviour in mind.

https://github.com/mrsteele/dotenv-webpack/blob/bf50d8d9b6436357e183a1ff285427e387cb5b35/test/index.test.js#L410

**Comment by mrsteele** [comment] 2022-01-16 02:26
You are saying when this plug-in is run it replaced your NODE_ENV, or webpack does (sorry, just want to make sure I understand correctly).

**Comment by mrsteele** [comment] 2022-05-06 13:09
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2022-05-06 13:09 UTC
