### ISSUE TITLE
Allow specification of particular systemVars to allow

### ISSUE THREAD

**Issue by brett-east** [mrsteele/dotenv-webpack#204] opened 2020-07-14 18:59 UTC
I'm trying to pass in `SHORT_SHA=$(echo $(git rev-parse --short HEAD))`
as a variable in my deploy npm script.

```
export SHORT_SHA=$(echo $(git rev-parse --short HEAD))
npm run deploy:staging
```
Or even:
```
SHORT_SHA=$(echo $(git rev-parse --short HEAD)) npm run deploy:staging
```

Where
`"deploy:staging": "npm run build:server:staging && npm run build:staging",`

and
`"build:server:staging": "env NODE_ENV=development DOT_ENV=staging webpack --config webpack.server.config.ts",`

and:
`"build:staging": "env NODE_ENV=development DOT_ENV=staging webpack",`

But I lose `$SHORT_SHA` in my webpack file because it's not in my `.env`,
I can access it in webpack, but not in my app.

Trying this works:
```
    new Dotenv({
      path: mode === 'production' ? '.env' : `.env.${dotEnv}`,
      systemvars: true,
    }),
```

But I don't want to just let all systemvars through, in case something is set locally
that interferes with the `.env`. But in this case I know that `SHORT_SHA` is one
that I want to allow.

Is there a way to specify an array of system vars that are allowed?

Or is there an even more obvious solution to allow this? It would seem that this is
a super common thing that people would want to do, how else are people getting 
variable env vars into their codebases?

Thanks very much,

**Comment by mrsteele** [comment] 2020-08-15 01:45
@brett-east Unfortunately its not built-in, however I think you could hack something together for your specific use-case.

if you did something like the following I believe it could work:
```js
const tempDotenv = new Dotenv({
  path: mode === 'production' ? '.env' : `.env.${dotEnv}`
})

tempDotenv.definitions['process.env.SHORT_SHA'] = process.env.SHORT_SHA

... // within the config object, use this customized instance instead of the usual approach
plugins: tempDotenv
```

Let me know if that fixes it!

**Comment by tysonmatanich** [comment] 2020-10-21 23:11
It would be awesome if `systemvars` could also take an array of allowed system variables:

```js
new Dotenv({
  path: '.env',
  systemvars: ['VAR1', 'VAR2', 'VAR3'],
}),
```

**Comment by tysonmatanich** [comment] 2020-10-22 02:46
@mrsteele Added pull request #256 with the above functionality

**Comment by mrsteele** [comment] 2020-11-03 02:40
What exactly is the concern? The variables are not exposed to a client unless they are explicitly referenced. Even if you accidentally left in the line `console.log(process.env)` it wouldn't output anything because it wasn't explicitly referenced.

Are your users referencing something in an API you are writing? Even so this application has just as much access to your environment variables as any running process so if you are accidentally leaking something sensitive at runtime perhaps you need to clean your env before running a process. first. You can clean any system envs by writing `process.env.PASSWORD = ''`.

Happy to help if I knew more context.

**Comment by mrsteele** [comment] 2022-05-06 13:15
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2022-05-06 13:15 UTC
