### ISSUE TITLE
incompatibility ES6 +

### ISSUE THREAD

**Issue by navarrojava** [mrsteele/dotenv-webpack#153] opened 2018-11-19 17:44 UTC
When I use  es6 feature "destructing assignment", the variables do not work.

// It does not work
const { MY_VARIABLE } = process.env;

// It  work
const  MY_VARIABLE  = process.env.MY_VARIABLE;

I think a little tuning in the engine that extracts the variables can fix it.

**Comment by mrsteele** [comment] 2018-11-20 18:59
I would suggest you refer to this comment: https://github.com/mrsteele/dotenv-webpack/issues/70#issuecomment-316720414

We have done extensive research and it actually is fully supportive with es6, however the way that `webpack.DefinePlugin` works.

We can either leak all `process.env` variables every time you reference a single variable, or we can remove the ability to destruct your env variables. For the purposes of security we opted to use the former.

I am closing this as it is a duplicate of #70. Let me know if there is anything else.

**Closed by mrsteele** 2018-11-20 18:59 UTC
