### ISSUE TITLE
i'm not able to access .env variables please help me thanks in advance.

### ISSUE THREAD

**Issue by RAzaALy** [mrsteele/dotenv-webpack#481] opened 2021-12-17 13:44 UTC
webpack-common.js
### const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const Dotenv = require('dotenv-webpack');

const CURRENT_WORKING_DIR = process.cwd();

module.exports = {
  entry: [
    '@babel/polyfill',
    path.join(CURRENT_WORKING_DIR, 'client/app/index.js')
  ],
  resolve: {
    extensions: ['.js', '.json', '.css', '.scss', '.html'],
    alias: {
      app: 'client/MONGO_URIapp'
    }
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        loader: 'babel-loader',
        exclude: /(node_modules)/
      }
    ]
  },
  plugins: [
    new Dotenv({
      path:  path.resolve(__dirname,  './.env.expample')
    }),
    new CopyWebpackPlugin([
      {
        from: 'client/public'
      }
    ])
  ]
};
###

**Comment by RAzaALy** [comment] 2021-12-17 13:45
webpack 4

**Comment by mrsteele** [comment] 2022-01-16 02:28
How are you accessing the variables, and can you give us a glimpse of what your env file looks like?

(also, it’s a bit concerning you are using an example file for your actual envs, I’m imagining that may just be a placeholder during development).

**Comment by mrsteele** [comment] 2022-05-06 13:10
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2022-05-06 13:10 UTC

**Comment by afsheen-a** [comment] 2022-08-22 04:57
Facing the same issue. My configurations are:
webpack.config.js:
```
plugins: [
      new DotEnv({ path: `./.env.${env.env}`, systemvars: true }),
      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, 'public'),
            to: path.resolve(__dirname, 'dist'),
          },
        ],
      }),
    ],
```

.env.local:

```API_BASE_URL=https://my-url```

index.js:

```
const BASE_URL = process.env.API_BASE_URL;
console.log(BASE_URL) //this gives me an empty object
```

**Comment by afsheen-a** [comment] 2022-08-22 05:04
Not sure what I need to change, thanks for any help/input you have!
