### ISSUE TITLE
🐓 [bug] after update to v2 -> v3 "SyntaxError: Unexpected token '.'"

### ISSUE THREAD

**Issue by thisVioletHydra** [mrsteele/dotenv-webpack#240] opened 2020-09-23 19:15 UTC
```
[INFO] 22:11:43 Restarting
SyntaxError: Unexpected token '.'
    at Object../src/server/server.production.js (C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:1778:1)
    at __webpack_require__ (C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:2089:32)
    at fn (C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:2225:21)
    at eval (webpack-internal:///./src/index.js:7:83)
    at Module../src/index.js (C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:1514:1)
    at __webpack_require__ (C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:2089:32)
    at C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:2992:11
    at Object.<anonymous> (C:\FRONTEND\www\group-dashboard\group-dashboard-api\dist\main.js:2993:12)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[ERROR] 22:11:43 SyntaxError
```

and my process.env = empty

**Comment by thisVioletHydra** [comment] 2020-09-23 19:19
```
  new Dotenv({
        path: resolve(process.cwd(), '.access/.env'),

        safe: true, // load '.env.example' to verify the '.env' variables are all set. Can also be a string to a different file.
        allowEmptyValues: true, // allow empty variables (e.g. `FOO=`) (treat it as empty string, rather than missing)
        systemvars: true, // load all the predefined 'process.env' variables which will trump anything local per dotenv specs.
        silent: false, // hide any errors
        defaults: false, // load '.env.defaults' as the default values if empty.),
      }),
```
Any settings don't help me, nothing works

**Comment by jorge-ui** [comment] 2020-09-23 20:48
I got `Uncaught SyntaxError: Unexpected token ':'`

And here it is in bundle.js:
![image](https://user-images.githubusercontent.com/47463822/94067983-998c2900-fdbc-11ea-9eb4-87e143f5081e.png)

**Comment by vladiiliev** [comment] 2020-09-24 10:33
Same here

**Comment by marklai1998** [comment] 2020-09-24 10:36
same here

**Comment by gatzjames** [comment] 2020-09-24 21:06
Had the same issue and think that's the code responsible for this issue:
https://github.com/mrsteele/dotenv-webpack/blob/7749894d0398f2f92300fa26666b60dd49e66abb/src/index.js#L144

Not idea why it supports webpack 5 but the docs on [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) state that defining `process: { env: { NODE_ENV: JSON.stringify('production') } }` will overwrite the process object which in turn removes webpack's polyfills for node's global process object.

**Comment by TrejGun** [comment] 2020-09-25 01:05
i have similar error but not same

```
ERROR in vendors.js from Terser
Unexpected token: punc (:) [~/node_modules/setimmediate/setImmediate.js:80,12][vendors.js:173914,18]
```

**Comment by emanuel-lundman** [comment] 2020-09-25 10:28
Big issue yes, everything broke, process overwritten and hence not available in node app and it's dependencies anymore.

**Comment by BeeeQueue** [comment] 2020-09-25 10:49
The issue is that Webpack 5 removes node polyfills including `process`, meaning if you have any `process.env` usage that didn't get replaced by `DefinePlugin` or `EnvironmentPlugin` (that this plugin uses) you will end up with a `cannot access property env of undefined`.

The mistake was to not make the fix for this only happen when using Webpack 5.

#241 will not solve the issue in Webpack 5.

**Comment by emanuel-lundman** [comment] 2020-09-25 12:17
@BeeeQueue does webpack5 replace/remove the whole process object even when targeting node? 
That's what happened for us. 
All process.xxx commands stopped working.

**Comment by BeeeQueue** [comment] 2020-09-25 12:23
It's only a polyfill, so afaik the Webpack 5 change should not have affected that unless this package's "fix" is actually breaking it.

**Comment by gatzjames** [comment] 2020-09-25 13:35
> The issue is that Webpack 5 removes node polyfills including `process`, meaning if you have any `process.env` usage that didn't get replaced by `DefinePlugin` or `EnvironmentPlugin` (that this plugin uses) you will end up with a `cannot access property env of undefined`.
> 
> The mistake was to not make the fix for this only happen when using Webpack 5.
> 
> #241 will not solve the issue in Webpack 5.

I think there are 2 issues.
One that in webpack 5 all node polyfills will be removed meaning that any code using process, global etc. will need to remove them or provide your own polyfill etc.
The other is that by providing the DefinePlugin with the value `process = '{"env": {}}'` will overwrite any value like `process.env.VAR_NAME: "someValue"` so any other plugin/user will not be able to add their own values.
So I think #241 will fix this issue for webpack 4 users and allow users of webpack 5 to provide process.env.variable with other plugins etc.
🤔

**Comment by BeeeQueue** [comment] 2020-09-25 13:40
I must've misunderstood how this plugin works, I'm not too knowledgable about it. 😅

**Comment by jakeleventhal** [comment] 2020-09-27 02:37
i see this too

**Comment by flo-sch** [comment] 2020-09-29 11:27
Same issue using webpack@4

Not sure if this plugin's v3.0.0 is meant to be only used with webpack >= 5.0.0 (in which case the release logs should probably mention it?), or is that the same bug?

**Comment by clairefro** [comment] 2020-09-30 22:25
What is the stable release version for use with Webpack 4?

**Comment by flo-sch** [comment] 2020-09-30 22:38
> What is the stable release version for use with Webpack 4?

The previous major version (2.3.2, locked as ^2.0.0) works fine for me with webpack 4

**Comment by ryancole** [comment] 2020-10-01 20:49
I think this v3 update breaks my webpack 4 build as well. It only seems to be breaking it when webpack mode is set to production, though. So we've only encountered issues after updating to v3 of dotenv-webpack recently and then testing a production build.

**Comment by asolopovas** [comment] 2020-10-07 11:33
Hi I am having this problem when upgrading from v1.7.0 to v3.0.0.
https://stackoverflow.com/questions/64232479/vue-js-webpack-i-get-setimmediate-js80-uncaught-syntaxerror-unexpected-token/64242919#64242919

**Comment by softmarshmallow** [comment] 2020-10-09 18:14
> > What is the stable release version for use with Webpack 4?
> 
> The previous major version (2.3.2, locked as ^2.0.0) works fine for me with webpack 4

Thanks man, 3.0.0 needs to be fixed.

**Comment by flo-sch** [comment] 2020-10-09 18:37
I guess yes, I am just not sure if:
- the v3 works with webpack5 (haven't tried webpack5 yet) or if it is broken (kinda look like a broken build to me, but I haven't been through the details)
- the v3 is not meant to be compatible with webpack4 (I would be surprised since it is still the stable version at the moment, and in that case the doc should probably mention it at least)

**Comment by Xunnamius** [comment] 2020-10-09 23:04
Also experiencing this. Downgrading as suggested earlier fixed this for me.

**Comment by Phebonacci** [comment] 2020-10-13 02:18
@flo-sch can confirm that it also doesn't work with webpack 5. We're getting the `Uncaught SyntaxError: Unexpected token ':'` error.

**Comment by flo-sch** [comment] 2020-10-13 06:36
Alright, does v2 still work with webpack5?

**Comment by evenfrost** [comment] 2020-10-16 11:02
@mrsteele any update?

**Comment by mrsteele** [comment] 2020-10-16 13:05
Wow, I'm so sorry everyone. My notifications got out of whack and I missed all of this. 

I just rolled-back the support for webpack 5. This should be released as `dotenv-webpack@v4.0.0` (essentially the same thing in `v2.0.0` with updated dependencies).

Because of this, anyone looking for support for webpack 5 wont have it. Any ideas?

**Comment by flo-sch** [comment] 2020-10-16 15:17
I have not tried webpack5 so far so  not sure what is needed, but I can have a look once I find the time to try it

From a strict versioning perspective, if the process.env API has significantly changed between webpack4 & webpack5, it may be difficult to maintain BC with webpack4 though...?

**Comment by BeeeQueue** [comment] 2020-10-16 17:03
The issue is that webpack 5 does not polyfill `process` anymore, so any `process.env.xxx` usage that does not get replaced by the plugin will give a runtime error when it tries to access `.env` on undefined.

The solution to this I'm currently running is to replace any remaining `process.env`s with `{}`, then it will not crash and will just return undefined.

**Comment by Enase** [comment] 2020-10-16 20:08
@BeeeQueue consider to replace it with proxy, something like:

```
const createProxy = (path = 'process.env') => new Proxy({}, {
  get: (target, name) => {
    const
    console.log(`WARNING: ${path}.${name} property is not set`);
    return createProxy(`${path}.${name}`);
  },
});
const valueToReplace = createProxy();
```

In this way:
- we log the issues (btw we can add some isDebugEnabled condition before console.log)
- we solve the issue when someone expect a deep object like `process.env.foo.bar.x`

**Comment by tx-steven** [comment] 2020-10-28 21:33
Any updates on this? I'm currently using this with webpack 5 and it works. I only receive a peer dep warning:

```npm ERR! peer dep missing: webpack@^1 || ^2 || ^3 || ^4, required by dotenv-webpack@4.0.0```

**Comment by sacummings91** [comment] 2020-10-28 21:39
Any updates on this? I'm currently using this with webpack 5 and it works. I only receive a peer dep warning:

npm ERR! peer dep missing: webpack@^1 || ^2 || ^3 || ^4, required by dotenv-webpack@4.0.0

It seems like the original update to v3 added code changes that break how process works in webpack. Is there something else I'm missing here that makes this more complicated than just adding || ^5 to supported versions?

**Comment by mrsteele** [comment] 2020-10-29 00:59
@sacummings91 I see it working too, just still no destructing: https://github.com/mrsteele/dotenv-webpack/pull/261

**Closed by mrsteele** 2020-10-29 00:59 UTC

**Comment by flo-sch** [comment] 2020-10-31 20:33
Hi @mrsteele, would it be possible to summarize which versions are meant to be used for webpack@4 and webpack@5?

In case versions support differ, perhaps adding a note in the README would be interesting?

(sorry to bother you on this closed PR, just felt easier to ask in the context)

**Comment by mrsteele** [comment] 2020-10-31 22:19
@flo-sch they are actually all supported up to this version. The gotchas are still gotchas from v4 as they are on v5.

Fortunately nothing changed, except that in webpack v5 you get an error if you reference an undefined variable (that's on webpack because they removed support for declaring an empty process.env object when bundling).

**Comment by mrsteele** [comment] 2020-11-04 06:20
@flo-sch Can you downgrade to the problematic version and see if you can reproduce this bug?

I'm having trouble reproducing it and looking for others to help report back here: #268
