### ISSUE TITLE
Can't resolve `aws-sdk` (?) error while using this plugin with Netlify Functions

### ISSUE THREAD

**Issue by galkowskit** [mrsteele/dotenv-webpack#166] opened 2019-04-16 09:43 UTC
I'm getting the error below while using this package with Netlify Functions. Is there any reason it would cause `aws-sdk` errors anyway?
```
ERROR in (...)/node_modules/fsevents/node_modules/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'aws-sdk' in '(...)/node_modules/fsevents/node_modules/node-pre-gyp/lib'
```
Similar errors happen in `publish.js` and `info.js` files. The code works fine regardless of the error though.

**Comment by mrsteele** [comment] 2019-04-26 19:58
Hey @galkowskit, quite honestly not sure why this error would be happening and what specifically is causing it...

**Comment by mrsteele** [comment] 2020-08-15 01:52
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2020-08-15 01:52 UTC
