### ISSUE TITLE
Doesn't work with dynamic references to env vars

### ISSUE THREAD

**Issue by you-fail-me** [mrsteele/dotenv-webpack#115] opened 2018-03-07 17:07 UTC
Sample code:
```
const requiredEnv = [ 'VAR', 'ANOTHER_VAR' ];
const missingEnv = requiredEnv.filter(v => !process.env[v]);
```

This breaks with `dotenv-webpack`, seems like it handles only direct references well (like `process.env.MY_VAR`, but not dynamic ones, because does a text replace.

Is there a way around it?

**Comment by mrsteele** [comment] 2018-03-07 18:11
This is correct as we use [webpack.DefinePlugin](https://webpack.js.org/plugins/define-plugin/) under the hood. Because of this is essentially does an advanced "search and replace" for any references to `process.env.VAR`.

We have explored resolving other issues related to this as well (see https://github.com/mrsteele/dotenv-webpack/issues/70#issuecomment-316720414).

For right now to maintain extensibility with future webpack upgrades I do not see any way around this. Should webpack eventually change how DefinePlugin works we would of course have those ready to use immediately without any updates.

If you have any ideas though I would be more than happy to hear them and consider exploring them.

I will leave this open temporarily until we have an appropriate answer.

**Comment by mrsteele** [comment] 2018-03-12 17:11
I'm closing this as it is a duplicate of #70. Feel free to keep the conversation going over there.

**Closed by mrsteele** 2018-03-12 17:11 UTC
