### ISSUE TITLE
Need support Boolean in .env file

### ISSUE THREAD

**Issue by yarkovaleksei** [mrsteele/dotenv-webpack#94] opened 2017-12-07 13:09 UTC
If you write `DEBUG = false` in the file, then when checking `!!process.env.DEBUG //true`, since the value will be read as a **string** **("false").**

**Comment by mrsteele** [comment] 2017-12-07 14:11
This is by nature of `env` variables and has been discussed in #93.

By design: You should in your code do
```js
if (process.env.DEBUG) {
  // do your special debug stuff
}
```

And leave `DEBUG` out completely from your `.env` file.

Closing as this is a duplicate and has already been resolved.

**Closed by mrsteele** 2017-12-07 14:11 UTC
