### ISSUE TITLE
Error: Cannot find module './src'

### ISSUE THREAD

**Issue by JosNun** [mrsteele/dotenv-webpack#151] opened 2018-10-20 20:31 UTC
`dotenv-webpack` is throwing this error when I try to run webpack. My directory structure is as follows.

![screen shot 2018-10-20 at 4 24 54 pm](https://user-images.githubusercontent.com/7729878/47260215-e5bde880-d484-11e8-89cd-65f9d11ca71a.png)

Also, here's my stack trace
```
Error: Cannot find module './src'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/josiah/node_modules/dotenv-webpack/index.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

And also my wepack config

```
HtmlWebpackPlugin = require('html-webpack-plugin');
Dotenv = require('dotenv-webpack');
path = require('path');

const htmlPlugin = new HtmlWebpackPlugin({
  template: './src/index.html',
  filename: 'index.html'
})

module.exports = {
  devtool: 'source-map',
  entry: './src/index.js',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, '../public')
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.css$/,
        use: ['syle-loader', 'css-loader']
      }
    ]
  },
  resolve: {
    extensions: ['*', '.js', '.jsx']
  },
  devServer: {
    host: '0.0.0.0',
  },
  plugins: [
    htmlPlugin, 
    new Dotenv({
      path: path.resolve(__dirname, './.env')
    })
  ],
}
```

Any suggestions?

**Comment by mixmatrix** [comment] 2018-10-25 16:44
Try to install for dev-dependencies. 

`yarn add --dev dotenv-webpack` 
or 
`nom install --save-dev dotenv-webpack`

that's work for me.

**Comment by sunitJindal** [comment] 2018-12-26 12:57
@JosNun is your issue resolved? If yes, please close the issue.

**Comment by mrsteele** [comment] 2020-08-15 01:54
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2020-08-15 01:54 UTC

**Comment by fritzmonkey** [comment] 2021-03-31 01:08
I ran into this when setting up a new project. If you don't have `webpack` installed (despite being a peer dep), it throws a `MODULE_NOT_FOUND` error that is swallowed [here](https://github.com/mrsteele/dotenv-webpack/blob/master/index.js#L7), it then tries to require `./src` which isn't packaged. Logging this original error would make this a bit easier to catch.
