### ISSUE TITLE
Escape of shell special characters does not work properly

### ISSUE THREAD

**Issue by AlexPalaz** [mrsteele/dotenv-webpack#470] opened 2021-08-09 17:05 UTC
I'm using "dotenv-webpack": "^1.8.0"
My .env:
`API_CALL='https://api.call?\$language=en'`

In the local environment it works correctly. Output:

`https://api.call?$language=en`

but when I build with webpack the result is:

` https://api.call?\$language=en `

What could be?

my webpack:

```
      new Dotenv({
          path: `./.env.${env.production ? 'production' : 'development'}`
      }),
      new webpack.DefinePlugin({
          "process.env.PRODUCTION": env.production || !env.development,
          "process.env.NAME": JSON.stringify(require("./package.json").name),
          "process.env.VERSION": JSON.stringify(require("./package.json").version),
      }),
```

**Comment by mrsteele** [comment] 2021-08-29 14:21
Does it work when you just don't escape? I'm not sure I've run into this, but most likely because I'm not using these characters in ENVs I've worked with.

Happy to hear if the community has any recommendations as well.

**Comment by mrsteele** [comment] 2022-05-06 13:12
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2022-05-06 13:12 UTC
