### ISSUE TITLE
.env variables are not available in Uglifyjs.config.js 

### ISSUE THREAD

**Issue by chaityashah** [mrsteele/dotenv-webpack#168] opened 2019-04-22 13:06 UTC
Hello Team, 

I am using webpack@3.12.0 with Ionic-app-scripts @ 3.2.3 and I am using dotenv-webpack to load my .env.dev and .env.prod files depending on the build command. 

This files are loading fine however these variable only available after build completes and I can use them in my application modules. 

However I want to use them while building my application as 1 use-case is : I have customize ionic_uglifyjs where I need some variable depending on the build environment. Where I cannot access these variable as returns `undefined`. 

Can you please let me know, if am I missing anything or what kind of change to this plugin will make variables available during build time. 

Thanks,
Chaitya Shah

**Comment by mrsteele** [comment] 2019-04-26 20:00
Do you think tree-shaking might be making a factor? This plugin is really simple, in that it does nothing but search and replace the envs you define in your application.

**Comment by mrsteele** [comment] 2020-08-15 01:53
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2020-08-15 01:53 UTC
