### ISSUE TITLE
Yarn add issue

### ISSUE THREAD

**Issue by danielesalvatore** [mrsteele/dotenv-webpack#53] opened 2017-05-04 09:35 UTC
Hi to everyone,
I am experiencing the following warnings/error during the adding of the library to my projects during the building of the DLL. Please find more info below. The library works fine even with the error.

Warnings/errors
```
WARNING in ./~/chokidar/lib/fsevents-handler.js
Module not found: Error: Can't resolve 'fsevents' in '/home/daniele/repos/FAO/Follow up/ui/node_modules/chokidar/lib'
 @ ./~/chokidar/lib/fsevents-handler.js 7:17-36
 @ ./~/chokidar/index.js
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib ^.*$
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/browser.js
 @ dll FollowUpDeps

WARNING in ./~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/uglify-js/tools/node.js
24:11-32 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

WARNING in ./~/loader-runner/lib/loadLoader.js
3:2-28 Critical dependency: the request of a dependency is an expression

ERROR in (webpack)/lib/NormalModule.js
Module not found: Error: Can't resolve 'module' in '/home/daniele/repos/FAO/Follow up/ui/node_modules/webpack/lib'
 @ (webpack)/lib/NormalModule.js 8:21-38
 @ (webpack)/lib ^.*$
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/browser.js
 @ dll FollowUpDeps

```
Webpack is configured based on two files:
Webpack.base.config

```
/**
 * COMMON WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const Dotenv= require("dotenv-webpack");

module.exports = (options) => ({
    entry: options.entry,
    output: Object.assign({ // Compile into js/build.js
        path: path.resolve(process.cwd(), 'build'),
        publicPath: '/' + (process.env.PROFILE === "dev" || process.env.PROFILE === "demo"? process.env.PROFILE.toLowerCase() : "")
    }, options.output), // Merge with env dependent settings
    module: {
        rules: [
            {
                test: /\.js$/, // Transform all .js files required somewhere with Babel
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: options.babelQuery,
                },
            },
            {
                // Preprocess our own .css files
                // This is the place to add your own loaders (e.g. sass/less etc.)
                // for a list of loaders, see https://webpack.js.org/loaders/#styling
                test: /\.css$/,
                exclude: /node_modules/,
                use: ['style-loader', 'css-loader'],
            },
            {
                // Preprocess 3rd party .css files located in node_modules
                test: /\.css$/,
                include: /node_modules/,
                use: ['style-loader', 'css-loader'],
            },
            {
                test: /\.(eot|svg|otf|ttf|woff|woff2)$/,
                use: 'file-loader',
            },
            {
                test: /\.(jpg|png|gif)$/,
                use: [
                    'file-loader',
                    {
                        loader: 'image-webpack-loader',
                        options: {
                            progressive: true,
                            optimizationLevel: 7,
                            interlaced: false,
                            pngquant: {
                                quality: '65-90',
                                speed: 4,
                            },
                        },
                    },
                ],
            },
            {
                test: /\.html$/,
                use: 'html-loader',
            },
            {
                test: /\.json$/,
                use: 'json-loader',
            },
            {
                test: /\.(mp4|webm)$/,
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 10000,
                    },
                },
            },
        ],
    },
    plugins: options.plugins.concat([
        new webpack.ContextReplacementPlugin(/\.\/locale$/, 'empty-module', false, /js$/),

        new webpack.ProvidePlugin({
            // make fetch available
            fetch: 'exports-loader?self.fetch!whatwg-fetch',
        }),

        // Always expose NODE_ENV to webpack, in order to use `process.env.NODE_ENV`
        // inside your code for any environment checks; UglifyJS will automatically
        // drop any unreachable code.
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(process.env.NODE_ENV),
                PROFILE: JSON.stringify(process.env.PROFILE)
            },
        }),
        new webpack.NamedModulesPlugin(),
        new Dotenv({
            path : "./.env",
            safe: false
        })
    ]),
    resolve: {
        modules: ['app', 'node_modules'],
        extensions: [
            '.js',
            '.jsx',
            '.react.js',
        ],
        mainFields: [
            'browser',
            'jsnext:main',
            'main',
        ],
    },
    devtool: options.devtool,
    target: 'web', // Make web variables accessible to webpack, e.g. window
    performance: options.performance || {},
    node: {
        fs: "empty"
    }
});
```
webpack.prod.config
```
// Important modules this config uses
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
//const OfflinePlugin = require('offline-plugin');

module.exports = require('./webpack.base.babel')({
    // In production, we skip all hot-reloading stuff
    entry: [
        path.join(process.cwd(), 'app/app.js'),
    ],

    devtool: 'source-map',

    // Utilize long-term caching by adding content hashes (not compilation hashes) to compiled assets
    output: {
        filename: '[name].[chunkhash].js',
        chunkFilename: '[name].[chunkhash].chunk.js',
    },

    plugins: [

        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            children: true,
            minChunks: 2,
            async: true,
        }),

        // Minify and optimize the index.html
        new HtmlWebpackPlugin({
            template: 'app/index.html',
            minify: {
                removeComments: true,
                collapseWhitespace: true,
                removeRedundantAttributes: true,
                useShortDoctype: true,
                removeEmptyAttributes: true,
                removeStyleLinkTypeAttributes: true,
                keepClosingSlash: true,
                minifyJS: true,
                minifyCSS: true,
                minifyURLs: true,
            },
            inject: true,
        }),

        // Put it in the end to capture all the HtmlWebpackPlugin's
        // assets manipulations and do leak its manipulations to HtmlWebpackPlugin
        /* new OfflinePlugin({
         relativePaths: false,
         publicPath: '/' + (process.env.PROFILE ? process.env.PROFILE.toLowerCase() : ""),

         // No need to cache .htaccess. See http://mxs.is/googmp,
         // this is applied before any match in `caches` section
         excludes: ['.htaccess'],

         caches: {
         main: [':rest:'],

         // All chunks marked as `additional`, loaded after main section
         // and do not prevent SW to install. Change to `optional` if
         // do not want them to be preloaded at all (cached only when first loaded)
         additional: ['*.chunk.js'],
         },

         // Removes warning for about `additional` section usage
         safeToUseOptionalCaches: true,

         AppCache: false,
         }),*/
    ],

    performance: {
        assetFilter: (assetFilename) => !(/(\.map$)|(^(main\.|favicon\.))/.test(assetFilename)),
    },
});
```
Libs versions:

dotenv-webpack: v1.4.3
webpack: 2.4.1

Thank you very much for your support

**Comment by mrsteele** [comment] 2017-05-04 13:08
What is your node version?

**Comment by mrsteele** [comment] 2017-05-04 13:14
Your configurations look alright.

I googled it a bit, could it be related to this: https://github.com/aspnet/JavaScriptServices/issues/587

**Comment by mrsteele** [comment] 2017-06-01 13:21
Closing due to lack of participation and cannot reproduce.

**Comment by danielesalvatore** [comment] 2017-06-05 15:21
Hi @mrsteele sorry if it took long time to reply. 
Just for reference I am getting the error with the following settings:

```
$ node --version
v8.0.0
$ npm --version
5.0.0

```

**Comment by danielesalvatore** [comment] 2017-06-05 15:35
For further reference I solved as suggested [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/104#issuecomment-230266920)

**Comment by mrsteele** [comment] 2017-06-05 15:55
So you suggest putting webpack/related into devDependencies?

I am not totally aware of the impact that would make on this module but feel free to submit a PR and I can dig into it a little further.

**Comment by M1chaelTran** [comment] 2017-08-30 07:13
I ran into the same issue `Module not found: Error: Can't resolve 'module' ...`
Moving `dotenv-webpack` from dependencies to `devDependencies` fixed the error
Thanks @danielesalvatore

**Comment by mrsteele** [comment] 2017-08-30 13:01
@M1chaelTran and @danielesalvatore The problem you have exposed is dependent on how you use `dotenv-webpack` so it is not the fault of the plugin.

If your app builds static files into a `dist` or a `build` folder and deploys those files to production then you are correct, it is simply a dev dependency.

Since our context is webpack and the bundling/build phases, its probably a safe assumption most of us will exist in the development context. Because of this I will go ahead and update the docs to close this guy out.

Thanks!

**Closed** 2017-08-30 13:05 UTC
