### ISSUE TITLE
Broken version 1.4.3

### ISSUE THREAD

**Issue by usamaejaz** [mrsteele/dotenv-webpack#46] opened 2017-03-15 06:34 UTC
```
C:\Users\HP\CodeHell\test>gulp
module.js:471
    throw err;
    ^

Error: Cannot find module './src'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\HP\CodeHell\test\node_modules\dotenv-webpack\index.js:9:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

Version 1.4.3 installed using ```npm i dotenv-webpack --save``` gave the above error. Tried 1.4.2 and didnt have any issue with that.

**Comment by mrsteele** [comment] 2017-03-15 15:19
Normally you see that if there is a problem with the dist file, but I cannot get any errors locally.

You can see that line is right here: https://github.com/mrsteele/dotenv-webpack/blob/master/index.js#L9

```diff
'use strict'

let plugin
try {
  plugin = require('./dist').default
} catch (err) {
  if (err.code === 'MODULE_NOT_FOUND') {
    require('babel-register')
++  plugin = require('./src').default
  } else {
    console.log(err)
    process.exit(1)
  }
}

module.exports = plugin
```

Because of this I would probably need more information as it is running fine for me locally.

1. What is your `dotenv-webpack` config?
1. What is your node/npm version?
1. What version of webpack are you using?
1. Have you tried deleting your whole `node_modules` folder and then rerunning?

**Comment by mrsteele** [comment] 2017-03-16 18:23
Can anyone else confirm this is happening? I cannot reproduce.

**Comment by mrsteele** [comment] 2017-03-23 17:29
It has been over a week with no follow up. I am closing for now as I cannot reproduce.

**Comment by awci** [comment] 2017-11-01 14:50
Hi I am getting same error
npm version: 5.51
node version: 8.6.0
dotenv-webpack version: 1.5.4


Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/..../node_modules/dotenv-webpack/index.js:8:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by mrsteele** [comment] 2017-11-01 15:43
@awci can you make sure you have `dotenv-webpack` in your `dependencies` list in `package.json`?

Some people had similar problems when `dotenv-webpack` was in the `devDependencies`, so I just want to be sure.

Also, can you tell me more about your environment? You using gulp/babel/webpack version/?

**Comment by awci** [comment] 2017-11-01 15:48
I found the error Webpack is installed on global When I try to webpack it is giving an error about babel-register actually it is giving error about Webpack because it does not found webpack but try-catch disallow to see this error.

**Comment by mrsteele** [comment] 2017-11-01 15:51
It looked like you may have downloaded the source project and not the actual module from npm.

Be sure to run `npm i dotenv-webpack --save` in your project root to download the proper contents in your `node_modules` folder.

Perhaps you can also tell me whats in that folder:
```
cd node_modules/dotenv-webpack
ls
```

You should see a `dist` folder, otherwise you do not have the distribution files which are required for dotenv-webpack.

**Comment by awci** [comment] 2017-11-01 15:53
I installed with: `npm i dotenv-webpack --save`

ls:
`
drwxrwxr-x   2 awci awci  4096 Kas  1 17:41 dist/
-rw-rw-r--   1 awci awci   276 Kas  1 18:02 index.js
-rw-rw-r--   1 awci awci  1068 Tem 24 18:53 LICENSE
-rw-rw-r--   1 awci awci  3130 Kas  1 17:41 package.json
-rw-rw-r--   1 awci awci  3624 Tem 24 18:53 README.md
`

**Comment by mrsteele** [comment] 2017-11-01 15:55
Okay I can see you have a dist folder set up.

Is this project on github or elsewhere so I can have a look? Curious to see the project setup and if I can reproduce.

**Comment by awci** [comment] 2017-11-01 15:58
sorry, it is not public.

but you can try with global webpack
remove webpack dependencies from package.json
try
` npm prune `
`npm i -g webpack`
`webpack`

**Comment by liitfr** [comment] 2017-11-29 09:51
I confirm this issue as well. I'm working on a react project based on [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate). Sadly can't share repo neither since it's a private one.

I also did `npm i dotenv-webpack --save` (it's in dependencies) and `node_modules/dotenv-webpack` contains a `dist` folder. Version : 1.5.4

**Comment by liitfr** [comment] 2017-11-29 10:45
My bad, error was related to webpack `dllPlugin`. So I excluded `dotenv-webpack` this way   
```
  "dllPlugin": {
    "path": "node_modules/react-boilerplate-dlls",
    "exclude": [
      "chalk",
      "compression",
      "cross-env",
      "express",
      "ip",
      "minimist",
      "sanitize.css",
      "dotenv-webpack"
    ],
    "include": [
      "core-js",
      "lodash",
      "eventsource-polyfill"
    ]
  },
``` 
  
Now it works like a charm :)

**Comment by mrsteele** [comment] 2017-11-29 12:45
I would love nothing more than to fix this but my current assumption is that it’s interference from elsewhere.

**Comment by mrsteele** [comment] 2018-03-12 17:06
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Closed by mrsteele** 2018-03-12 17:06 UTC

**Comment by abutterworth** [comment] 2020-03-23 20:00
For anyone else seeing this, note that the real error is not being logged. In my case I was missing webpack (listed as a peer dependency). This causes an error to occur in `dist/index.js` when attempting to require webpack. This package will then behave as if it's in development mode and look for babel-register (which then in turn can error out and display the message we see above).

**Comment by perryraskin** [comment] 2020-12-21 15:17
I'm having this issue. I tried many of these solutions. I tried installing `dotenv-webpack` in peer dependencies, devDependencies, and i tried removing the `^` from the version number, in case Heroku was using a different version.

I keep running into this error no matter what I do. I even reverted my app back to how it was before any of this started happening, and it somehow still hits this error. I can't work on my app anymore since it will simply no longer deploy successfully.

Any further advice here would be greatly appreciated!

**Comment by marekfeikus** [comment] 2021-02-23 15:41
@mrsteele Hi, I got the same generic error. The real error is swallowed and shows this:
![image](https://user-images.githubusercontent.com/4778643/108867761-18b1b180-7628-11eb-8a44-4654c8678bf5.png)
![image](https://user-images.githubusercontent.com/4778643/108867838-2bc48180-7628-11eb-8bc0-5ea32546843b.png)

**Comment by mrsteele** [comment] 2021-02-23 16:14
Curious @marekfeikus if you can upgrade to our latest, we don't swallow the error in the latest.

**Comment by marekfeikus** [comment] 2021-02-23 16:26
@mrsteele Apollogies for not mentioning that it's happening at a current version `6.0.2`

**Comment by mrsteele** [comment] 2021-02-23 16:37
Well I guess I have two questions @marekfeikus:
1. Why is it being swallowed? You have an error during importing this module and we output here: https://github.com/mrsteele/dotenv-webpack/blob/master/index.js#L11
2. The error shouldn't happen if you have the `dist` folder right?

**Comment by marekfeikus** [comment] 2021-02-23 16:57
It goes to the `if err.code === 'MODULE_NOT_FOUND'` block but then does not provide info about which module is not found. I had to log it out manually to know that it's about `lib/RequestShortener`. 
```
'use strict'

let plugin
try {
  plugin = require('./dist').default
} catch (err) {
  console.log('err: ', err);
  if (err.code === 'MODULE_NOT_FOUND') {
    require('babel-register')
    plugin = require('./src').default
  } else {
    console.log(err)
    process.exit(1)
  }
}

module.exports = plugin
```

**Comment by mrsteele** [comment] 2021-02-23 17:12
@marekfeikus You will have to help me understand. If you try in run `plugin = require('./dist').default` and it fails, its generally because `MODULE_NOT_FOUND` happened (meaning, the `./dist/index.js`) file didn't load.

You are right in that there could be something INSIDE their that didn't load, which I guess sounds plausible. Ultimately did you not have `webpack` or something similar loaded that should have been? The only dependencies in that file are `dotenv-defaults`, `fs` and `webpack`. Perhaps those or something in your tree were not included?

Truthfully I have always wanted to just point `main` to `dist` anyways as I no longer use the "dev" workflow this used to support, perhaps thats really all that should be done so it will fail naturally but also curious why these are failing when you only need to include this package as well as `webpack` as a peerDependency.

**Comment by marekfeikus** [comment] 2021-02-24 02:15
@mrsteele I guess i have to look more on what's `netlify-lambda build` is doing under the hood, because as you're pointing out, there's no reason for it not to work (I have all the deps)...I'll see how much time I'll have to dig deeper to solve this issue, but now I'm thinking it has nothing to do with this lib itself actually. Thanks a lot for the replies.

**Comment by mrsteele** [comment] 2021-02-24 03:43
Thanks @marekfeikus , i'd love to get to the bottom of this but really struggling to grasp what exactly is going on.

**Comment by abutterworth** [comment] 2021-02-24 04:22
Is the root issue here that you can enter the catch block inappropriately? The only `MODULE_NOT_FOUND` error that should be caught is the original require('dist') not any inner require. It might be worth testing for "development mode" by wrapping [require.resolve](https://nodejs.org/api/modules.html#modules_require_resolve_request_options) in a try catch rather than `require`. Maybe something like?

```
'use strict'

function distModuleExists() {
  try {
    require.resolve('./dist');
    return true;
  } catch (err) {
    return false;
  }
}

let plugin

if (distModuleExists()) {
  plugin = require('./dist').default
} else {
  require('babel-register')
  plugin = require('./src').default
}

module.exports = plugin
```

**Comment by mrsteele** [comment] 2021-02-24 04:48
@abutterworth That is the root problem. Why other modules are showing up is the question....

**Comment by dandrei** [comment] 2021-02-27 17:06
I first started getting this after upgrading some libraries in `package.json`, which must have removed `webpack` as a dependency. I fixed this by explicitly requiring `webpack` in my `package.json`.

**Comment by mrsteele** [comment] 2021-02-27 18:18
Thanks for sharing @dandrei, yeah it is required as a peerDependency so very possible to mess things up if it's not explicitly included.
